# Docker
- task: kiuwan-baseline-analysis-task@2
  inputs:
    kiuwanConnection: 'Kiuwan Dan'
    projectnameselector: 'kiuwanapp'
    kiuwanappname: 'Android App'
    analysislabel: 'Azure'
    includeinsight: true
    uploadsnippets: true
    uploadfiles: false
    skipclones: false
    overridedotkiuwan: false
    overrideappmodel: false
    dbanalysis: false
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
